apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: WireguardPeer
metadata:
  name: wireguardpeer-sample
spec:
  wireguardRef: wireguard-sample
  publicKey: "<public-key>"
  address: "10.0.0.2/32"
  persistentKeepalive: 25
